### ISSUE TITLE
Lists need a space after them.

### ISSUE THREAD

**Issue by jstac** [executablebooks/quantecon-example#2]
See,  e.g., "The best such distribution is Anaconda" in https://executablebookproject.github.io/quantecon-example/docs/getting_started.html.

There should be a space above this line.

**Comment by jstac** [comment]
Also, on the same page, the "Note" should have some white space above it.

**Comment by najuzilu** [comment]
@jstac I can't decide if this is something we should report as a bug or not. I tried to insert a couple of newlines but did not fix the issue. I then added `<br />` and that fixed it.

**Comment by mmcky** [comment]
I agree -- more padding is required around `Notes` etc. This is typically controlled by the theme. Extra lines int he source files won't work as they are ignored.
