### ISSUE TITLE
Combinations of Packages Issue?

### ISSUE THREAD

**Issue by mmcky** [executablebooks/quantecon-example#4]
I just installed `cli`, `myst-nb`, `sphinx-jupyter-book-theme` and I can't get this repository to build using `cli` tool. 

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/8263752/78099701-7ba5c300-742e-11ea-90cd-7e24976c6e33.png">

@chrisjsewell I did install `myst-parser==0.8.0a3`.

**Comment by mmcky** [comment]
Ok an update I have now used `pip install -e .` in all the repos (rather than using `pip` directly) and `myst-parser==0.8.0.0a3`

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/8263752/78099987-46e63b80-742f-11ea-9819-11c7118df6f9.png">

**Comment by najuzilu** [comment]
Did you install [sphinx-book-theme](https://github.com/ExecutableBookProject/sphinx-book-theme)?

**Comment by najuzilu** [comment]
I just ran the following steps twice and it works in both cases:
1. `conda create -n testEnv pip`
2. in `cli` repo: `~/opt/anaconda3/envs/testEnv/bin/pip install -e.`
3. post-env-act: `jb build book/`
<img width="658" alt="Screen Shot 2020-04-01 at 3 54 13 PM" src="https://user-images.githubusercontent.com/33075058/78100646-0a1b4400-7431-11ea-97de-7b6ef668889f.png">

**Comment by najuzilu** [comment]
@mmcky I'm closing this issue since I have provided information on how to create a conda environment in the readme file.
