### ISSUE TITLE
more space between code cells and figures?

### ISSUE THREAD

**Issue by jstac** [executablebooks/quantecon-example#5]
Do others agree that there should be more space between code cells and the figures they generate?

https://executablebookproject.github.io/quantecon-example/docs/matplotlib.html

CC @najuzilu @choldgraf

**Comment by choldgraf** [comment]
I agree, though I think this is jupyter sphinx, let's see how it looks when @najuzilu converts these to code-cell directives

**Comment by jstac** [comment]
Looks like it's already converted: 

https://raw.githubusercontent.com/ExecutableBookProject/quantecon-example/master/book/docs/matplotlib.md

**Comment by choldgraf** [comment]
Huh, well, then I still agree with you 😁

**Comment by chrisjsewell** [comment]
In terms of cell input/output spacing, we might need to consider if there needs to be any dynamic logic, whereby the spacing depends on what comes before/after. Maybe not but just to note

**Comment by choldgraf** [comment]
@chrisjsewell yeah I agree...we can play around with the CSS to get it looking right

**Comment by jstac** [comment]
In that case I think tables should be added to the list, when this logic is applied:

https://executablebookproject.github.io/quantecon-example/docs/pandas.html

The need is less than it is for figures, but a bit of space would still be a visual improvement.

(I have to say though, the theme is beautiful overall.  The lectures @najuzilu put together look fantastic.)
